import = [
    "~/.config/alacritty/themes/themes/one_dark.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
opacity = 1
blur = false

[window.dimensions]
columns = 95
lines = 25

[window.padding]
x = 4
y = 4

[font]
size = 10.0

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[selection]
save_to_clipboard = false
